services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    image: nginx
    restart: on-failure
    networks:
      - inception_network
    ports:
      - "443:443"
      # - "80:80"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    image: wordpress
    restart: unless-stopped
    networks:
      - inception_network
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_SITE_URL: ${DOMAIN_NAME}
      WORDPRESS_SITE_TITLE: ${WORDPRESS_SITE_TITLE}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      USER_USERNAME: ${USER_USERNAME}
      USER_EMAIL: ${USER_EMAIL}
      USER_PASSWORD: ${USER_PASSWORD}
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    image: mariadb
    restart: unless-stopped
    networks:
      - inception_network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: ${HOME}/data/html
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: ${HOME}/data/mariadb

networks:
  inception_network:
    driver : bridge